<?php
declare(strict_types=1);
/* RAZE RUSSIA VK BOT - expanded command build for Bothost.
 * Uses VK Groups Long Poll + SQLite. messages.send intentionally has NO reply_to.
 */

fwrite(STDOUT,"=== RAZE RUSSIA BOT FULL BUILD - NO REPLY_TO ===\n");
$token=trim((string)getenv('VK_TOKEN')); $groupId=(int)getenv('VK_GROUP_ID');
$ownerIds=array_values(array_filter(array_map('intval',preg_split('/[,;\s]+/',trim((string)getenv('OWNER_IDS'))?:''))));
date_default_timezone_set(trim((string)getenv('TZ'))?:'Europe/Moscow');
if($token===''||$groupId<=0){fwrite(STDERR,"ERROR: set VK_TOKEN and VK_GROUP_ID\n");exit(1);} if(!extension_loaded('pdo_sqlite')){fwrite(STDERR,"ERROR: pdo_sqlite extension is not loaded\n");exit(1);}

function vk(string $m,array $p=[]):array{global $token;$p['access_token']=$token;$p['v']='5.199';$u='https://api.vk.com/method/'.$m.'?'.http_build_query($p);$c=stream_context_create(['http'=>['timeout'=>35,'ignore_errors'=>true]]);$r=@file_get_contents($u,false,$c);if($r===false)return['error'=>['error_msg'=>'VK API request failed']];$j=json_decode($r,true);return is_array($j)?$j:['error'=>['error_msg'=>'Invalid VK response']];}
function sendMessage(int $peer,string $text):bool{$r=vk('messages.send',['peer_id'=>$peer,'random_id'=>random_int(-2147483648,2147483647),'message'=>$text]);if(isset($r['error'])){fwrite(STDERR,'SEND ERROR: '.json_encode($r['error'],JSON_UNESCAPED_UNICODE)."\n");return false;}fwrite(STDOUT,"SENT to {$peer}\n");return true;}
function sendUser(int $uid,string $text):bool{return sendMessage($uid,$text);}
function sendMessageKeyboard(int $peer,string $text,array $keyboard):bool{global $token;$r=vk('messages.send',['peer_id'=>$peer,'random_id'=>random_int(-2147483648,2147483647),'message'=>$text,'keyboard'=>json_encode($keyboard,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);if(isset($r['error'])){fwrite(STDERR,'SEND ERROR: '.json_encode($r['error'],JSON_UNESCAPED_UNICODE)."\n");return false;}return true;}
function sendHelp(int $peer):void{$keyboard=['inline'=>1,'buttons'=>[[['action'=>['type'=>'open_link','link'=>'http://vk.ru/@-241953865-cmd','label'=>'📚 Команды']]]]];sendMessageKeyboard($peer,'🤖 RAZE RUSSIA — помощь\n\nПолный список команд и их описание доступны здесь.', $keyboard);}
function startupCheck():void{global $groupId;$r=vk('groups.getById',['group_id'=>$groupId]);if(isset($r['error'])){fwrite(STDERR,'VK getById ERROR: '.json_encode($r['error'],JSON_UNESCAPED_UNICODE)."\n");return;}$g=$r['response']['groups'][0]??[];fwrite(STDOUT,'VK group: '.($g['name']??'unknown')." (#{$groupId})\n");$s=vk('groups.setLongPollSettings',['group_id'=>$groupId,'api_version'=>'5.199','enabled'=>1,'message_new'=>1,'message_reply'=>0,'message_allow'=>0,'message_deny'=>0,'message_edit'=>0,'message_event'=>0,'message_typing_state'=>0,'message_reaction_event'=>0,'message_reaction_new'=>0,'message_reaction_remove'=>0]);if(isset($s['error']))fwrite(STDERR,'Long Poll settings ERROR: '.json_encode($s['error'],JSON_UNESCAPED_UNICODE)."\n");else fwrite(STDOUT,"Long Poll: message_new enabled\n");}

$db=__DIR__.'/data/raze.sqlite';if(!is_dir(dirname($db)))mkdir(dirname($db),0775,true);$pdo=new PDO('sqlite:'.$db);$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);$pdo->exec('PRAGMA journal_mode=WAL');$pdo->exec('PRAGMA busy_timeout=5000');
$pdo->exec(<<<SQL
CREATE TABLE IF NOT EXISTS roles(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,priority INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS chat_users(id INTEGER PRIMARY KEY AUTOINCREMENT,peer_id INTEGER NOT NULL,user_id INTEGER NOT NULL,role_id INTEGER NOT NULL DEFAULT 1,nickname TEXT,immunity INTEGER NOT NULL DEFAULT 0,last_seen TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,messages INTEGER NOT NULL DEFAULT 0,UNIQUE(peer_id,user_id));
CREATE TABLE IF NOT EXISTS chat_settings(peer_id INTEGER PRIMARY KEY,rules TEXT,welcome TEXT,silence_until TEXT,games_enabled INTEGER NOT NULL DEFAULT 0,automod_enabled INTEGER NOT NULL DEFAULT 0,mentions_enabled INTEGER NOT NULL DEFAULT 1,report_notify_peer INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS warnings(id INTEGER PRIMARY KEY AUTOINCREMENT,peer_id INTEGER NOT NULL,user_id INTEGER NOT NULL,moderator_id INTEGER NOT NULL,reason TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bans(id INTEGER PRIMARY KEY AUTOINCREMENT,peer_id INTEGER NOT NULL,user_id INTEGER NOT NULL,moderator_id INTEGER NOT NULL,days INTEGER NOT NULL,reason TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,expires_at TEXT);
CREATE TABLE IF NOT EXISTS mutes(id INTEGER PRIMARY KEY AUTOINCREMENT,peer_id INTEGER NOT NULL,user_id INTEGER NOT NULL,moderator_id INTEGER NOT NULL,minutes INTEGER NOT NULL,reason TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,expires_at TEXT);
CREATE TABLE IF NOT EXISTS logs(id INTEGER PRIMARY KEY AUTOINCREMENT,peer_id INTEGER NOT NULL,actor_id INTEGER NOT NULL,target_id INTEGER,action TEXT NOT NULL,details TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS nicknames(id INTEGER PRIMARY KEY AUTOINCREMENT,peer_id INTEGER NOT NULL,user_id INTEGER NOT NULL,nickname TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(peer_id,user_id));
CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY AUTOINCREMENT,peer_id INTEGER NOT NULL,user_id INTEGER NOT NULL,text TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,assigned_to INTEGER,closed_at TEXT);
CREATE TABLE IF NOT EXISTS report_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,report_id INTEGER NOT NULL,user_id INTEGER NOT NULL,text TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS economy(peer_id INTEGER NOT NULL,user_id INTEGER NOT NULL,balance INTEGER NOT NULL DEFAULT 1500,country TEXT,partner_id INTEGER,registered_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_bonus TEXT,last_casino TEXT,PRIMARY KEY(peer_id,user_id));
CREATE TABLE IF NOT EXISTS marriages(peer_id INTEGER NOT NULL,user1 INTEGER NOT NULL,user2 INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(peer_id,user1,user2));
CREATE TABLE IF NOT EXISTS countries(peer_id INTEGER NOT NULL,name TEXT NOT NULL,owner_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(peer_id,name));
CREATE TABLE IF NOT EXISTS unities(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,owner_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS unity_chats(unity_id INTEGER NOT NULL,peer_id INTEGER NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS superusers(user_id INTEGER PRIMARY KEY,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS schedules(id INTEGER PRIMARY KEY AUTOINCREMENT,peer_id INTEGER NOT NULL,owner_id INTEGER NOT NULL,every_minutes INTEGER NOT NULL,text TEXT NOT NULL,next_at TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,global_flag INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS listenings(peer_id INTEGER PRIMARY KEY,owner_id INTEGER NOT NULL,expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS bot_meta(k TEXT PRIMARY KEY,v TEXT);
SQL);
$pdo->exec("INSERT OR IGNORE INTO roles(id,name,priority) VALUES(1,'Участник',0),(2,'Помощник',20),(3,'Модератор',40),(4,'Администратор',60),(5,'Ст. администратор',80),(6,'Владелец',100)");
function ensureColumn(PDO $p,string $table,string $column,string $definition):void{
    $cols=$p->query("PRAGMA table_info(\"".$table."\")")->fetchAll(PDO::FETCH_COLUMN,1);
    if(!in_array($column,$cols,true)){$p->exec("ALTER TABLE \"{$table}\" ADD COLUMN \"{$column}\" {$definition}");}
}
ensureColumn($pdo,'chat_users','messages','INTEGER NOT NULL DEFAULT 0');
ensureColumn($pdo,'chat_settings','mentions_enabled','INTEGER NOT NULL DEFAULT 1');
ensureColumn($pdo,'chat_settings','report_notify_peer','INTEGER NOT NULL DEFAULT 0');
ensureColumn($pdo,'reports','assigned_to','INTEGER');
ensureColumn($pdo,'reports','closed_at','TEXT');


function ensureUser(PDO $p,int $peer,int $uid):void{$s=$p->prepare("INSERT INTO chat_users(peer_id,user_id,role_id,last_seen) VALUES(?,?,1,CURRENT_TIMESTAMP) ON CONFLICT(peer_id,user_id) DO UPDATE SET last_seen=CURRENT_TIMESTAMP,messages=messages+1");$s->execute([$peer,$uid]);$e=$p->prepare('INSERT OR IGNORE INTO economy(peer_id,user_id) VALUES(?,?)');$e->execute([$peer,$uid]);}
function priority(PDO $p,int $peer,int $uid):int{$s=$p->prepare('SELECT r.priority FROM chat_users u JOIN roles r ON r.id=u.role_id WHERE u.peer_id=? AND u.user_id=?');$s->execute([$peer,$uid]);return(int)($s->fetchColumn()?:0);}
function isSuper(int $uid):bool{global $pdo,$ownerIds;if(in_array($uid,$ownerIds,true))return true;$s=$pdo->prepare('SELECT 1 FROM superusers WHERE user_id=?');$s->execute([$uid]);return(bool)$s->fetchColumn();}
function level(PDO $p,int $peer,int $uid):int{return isSuper($uid)?100:priority($p,$peer,$uid);}
function loga(PDO $p,int $peer,int $actor,?int $target,string $action,string $details=''):void{$s=$p->prepare('INSERT INTO logs(peer_id,actor_id,target_id,action,details) VALUES(?,?,?,?,?)');$s->execute([$peer,$actor,$target,$action,$details]);}
function expire(PDO $p):void{$p->exec("UPDATE bans SET active=0 WHERE active=1 AND expires_at IS NOT NULL AND expires_at<=datetime('now')");$p->exec("UPDATE mutes SET active=0 WHERE active=1 AND expires_at IS NOT NULL AND expires_at<=datetime('now')");}
function parseCommand(string $t):array{$t=trim($t);if($t==='')return['',[]];$t=preg_replace('/^[!\/.]+/u','',$t);$a=preg_split('/\s+/u',$t);return[mb_strtolower((string)array_shift($a)),$a];}
function target(array $o,array $a):?int{if(isset($o['reply_message']['from_id']))return abs((int)$o['reply_message']['from_id']);if(!empty($a[0])&&preg_match('/^\[id(\d+)\|/i',$a[0],$m))return(int)$m[1];if(!empty($a[0])&&preg_match('/^(?:id)?(\d+)$/i',$a[0],$m))return(int)$m[1];if(!empty($a[0])&&preg_match('/(?:vk\.com\/id|id)(\d+)/i',$a[0],$m))return(int)$m[1];return null;}
function nameOf(int $uid):string{$r=vk('users.get',['user_ids'=>$uid,'fields'=>'first_name,last_name']);$u=$r['response'][0]??[];return trim(($u['first_name']??'').' '.($u['last_name']??''))?:"ID {$uid}";}
function targetName(int $uid):string{return nameOf($uid);}
function ensureEconomy(PDO $p,int $peer,int $uid):void{$p->prepare('INSERT OR IGNORE INTO economy(peer_id,user_id) VALUES(?,?)')->execute([$peer,$uid]);}
function amount(string $s):int{$s=mb_strtolower(str_replace(['₽',' ',','],'',$s));$m=1;if(str_ends_with($s,'кк')){$m=1000000;$s=substr($s,0,-2);}elseif(str_ends_with($s,'к')){$m=1000;$s=substr($s,0,-1);}return max(0,(int)round((float)$s*$m));}
function rulesText(PDO $p,int $peer):string{$s=$p->prepare('SELECT rules FROM chat_settings WHERE peer_id=?');$s->execute([$peer]);return(string)($s->fetchColumn()?:'Правила беседы ещё не настроены.');}
function requireLevel(int $have,int $need,string $role):?string{return $have<$need?"🤖 У Вас недостаточно высокий приоритет для использования этой команды.\nНеобходимая роль: '{$role}' (№{$need}), ваша роль: №{$have}.":null;}
function punishAllowed(PDO $p,int $peer,int $actor,int $target,int $need):?string{$al=level($p,$peer,$actor);$tl=priority($p,$peer,$target);if($actor===$target)return'❌ Нельзя применить наказание к самому себе.';if($tl>=$al)return'❌ Вы не можете применить наказание к пользователю, роль которого выше или равна вашей.';$s=$p->prepare('SELECT immunity FROM chat_users WHERE peer_id=? AND user_id=?');$s->execute([$peer,$target]);if((int)($s->fetchColumn()?:0)===1&&$al<100)return'❌ У пользователя включён иммунитет.';return null;}
function helpText():string{return <<<TXT
**RAZE RUSSIA — команды**

**Общие:**
!помощь / !команды / !help — список команд.
!пинг / !статус — проверка работы.
!правила — правила беседы.
!роли — роли и приоритеты.
!админы — администрация.
!онлайн — участники онлайн.
!history — ваша история наказаний.
!thereid / !myid — ID беседы.
/report [текст] — жалоба/идея.
!упоминать / !неупоминать — настройки вызова.
!профиль — игровой профиль.
!бонус — ежедневный бонус.
!казино [ставка] — казино.
!перевод [ID] [сумма] — перевод.
!топ — топ балансов/сообщений.
!atop — общий топ.
!гражданство [страна], !страна, !страны.
!брак [ID], !развод, !браки.
!поцелуй [ID], !обнять [ID], !попытка [действие], !пиво.

**Помощник 20+:**
!мут [ID] [минуты] [причина]
!унмут [ID]
!кик [ID] [причина]
!пред / !варн [ID] [причина]
!унварн / !снятьпред [ID]
!предупреждения / !getwarns [ID]
!getwarn [ID]
!getban [ID]
!getmute [ID]
!warnlist / !преды
!бан [ID] [дни] [причина]
!унбан [ID]
!ник [ID], !сник [ID] [ник], !рник [ID]
!нлист, !безников
!вызов [текст]
!чатинфо
!reg [ID]

**Модератор 40+:**
!role [ID] [роль/приоритет]
!removerole [ID]
!помощник [ID], !модер [ID]
!тишина [время]
!понику [часть ника]
!gzov [текст], !gkick [ID], !gsnick [ID] [ник]

**Администратор 60+:**
!gban, !gunban, !grole, !гмодер, !гпомощник
!удалить, !gm, !removegm, !history [ID], !gms

**Ст. администратор 80+:**
!pin, !unpin, !admin, !gadmin, !newrole, !gnewrole, !delrole
!welcome, !setrules, !delrules, !неактив, !givemoney, !timeuved

**Владелец 100+:**
!settings, !setup, !unity / !addunity / !createunity / !editunity / !removeunity
!sync, !spec / !gspec, !wipe, !games, !editcmd / !geditcmd, !gedit
!gsettings, !owner, !automod, !addws

**Создатель/супер-доступ:**
!setlog, !zovvv, !addws, !gtimeuvedg, !gzovg
!reportedit, !getdialog, !getreport, !reports
!listunities, !listen, !chatlist, !userchats, !ahistory, !checkban
TXT;}

function doGlobal(PDO $p,int $peer,int $uid,string $action,callable $fn):void{$s=$p->query('SELECT peer_id FROM chat_settings')->fetchAll(PDO::FETCH_COLUMN);foreach($s as $other){try{$fn((int)$other);}catch(Throwable $e){}}}
function chatMembers(int $peer):array{$r=vk('messages.getConversationMembers',['peer_id'=>$peer,'fields'=>'online,first_name,last_name,is_admin,is_owner']);return $r['response']['items']??[];}
function syncChatRoles(PDO $p,int $peer):array{$members=chatMembers($peer);$owner=0;$admins=[];foreach($members as $m){$uid=(int)($m['member_id']??0);if($uid<=0)continue;ensureUser($p,$peer,$uid);if(!empty($m['is_owner']))$owner=$uid;if(!empty($m['is_admin']))$admins[]=$uid;}if($owner>0){$p->prepare('UPDATE chat_users SET role_id=6 WHERE peer_id=? AND user_id=?')->execute([$peer,$owner]);}foreach($admins as $uid){if($uid===$owner)continue;$p->prepare('UPDATE chat_users SET role_id=5 WHERE peer_id=? AND user_id=? AND role_id<5')->execute([$peer,$uid]);}return[$owner,$admins];}
function handleChatAction(PDO $p,int $peer,array $o):void{$a=$o['action']??null;if(!is_array($a))return;$type=(string)($a['type']??'');$member=(int)($a['member_id']??0);if(!in_array($type,['chat_invite_user','chat_invite_user_by_link'],true))return;syncChatRoles($p,$peer);$q=$p->prepare('SELECT welcome FROM chat_settings WHERE peer_id=?');$q->execute([$peer]);$welcome=(string)($q->fetchColumn()?:'');if($welcome!=='')sendMessage($peer,$welcome);if($member>0)ensureUser($p,$peer,$member);}
function mentionAll(PDO $p,int $peer,string $text):void{$m=chatMembers($peer);$ids=[];foreach($m as $x){$id=(int)($x['member_id']??0);if($id>0)$ids[]=$id;}if(!$ids){sendMessage($peer,$text);return;} $out=$text."\n";foreach(array_slice($ids,0,100) as $id)$out.="[id{$id}|. ] ";sendMessage($peer,$out);}
function sendScheduled(PDO $p):void{$now=date('Y-m-d H:i:s');$s=$p->prepare('SELECT * FROM schedules WHERE active=1 AND next_at<=?');$s->execute([$now]);foreach($s as $row){sendMessage((int)$row['peer_id'],$row['text']);$next=date('Y-m-d H:i:s',time()+((int)$row['every_minutes']*60));$p->prepare('UPDATE schedules SET next_at=? WHERE id=?')->execute([$next,$row['id']]);}}

function handle(PDO $p,array $o):void{
 global $ownerIds,$groupId;
 $peer=(int)($o['peer_id']??0);$from=(int)($o['from_id']??0);$text=trim((string)($o['text']??''));
 if(!$peer||!$from)return;fwrite(STDOUT,"EVENT message_new peer={$peer} from={$from} text=".json_encode($text,JSON_UNESCAPED_UNICODE)."\n");ensureUser($p,$peer,$from);expire($p);[$cmd,$a]=parseCommand($text);if($cmd==='')return;
 $L=level($p,$peer,$from);$target=target($o,$a);$req=[
 'пинг'=>[0,'Участник'],'ping'=>[0,'Участник'],'статус'=>[0,'Участник'],'help'=>[0,'Участник'],'помощь'=>[0,'Участник'],'команды'=>[0,'Участник'],'start'=>[0,'Участник'],'правила'=>[0,'Участник'],'роли'=>[0,'Участник'],'админы'=>[0,'Участник'],'онлайн'=>[0,'Участник'],'history'=>[0,'Участник'],'myid'=>[0,'Участник'],'thereid'=>[0,'Участник'],'id'=>[0,'Участник'],'report'=>[0,'Участник'],'профиль'=>[0,'Участник'],'проф'=>[0,'Участник'],'бонус'=>[0,'Участник'],'bonus'=>[0,'Участник'],'казино'=>[0,'Участник'],'перевод'=>[0,'Участник'],'топ'=>[0,'Участник'],'top'=>[0,'Участник'],'atop'=>[0,'Участник'],'гражданство'=>[0,'Участник'],'страна'=>[0,'Участник'],'страны'=>[0,'Участник'],'брак'=>[0,'Участник'],'развод'=>[0,'Участник'],'браки'=>[0,'Участник'],'поцелуй'=>[0,'Участник'],'kiss'=>[0,'Участник'],'обнять'=>[0,'Участник'],'попытка'=>[0,'Участник'],'пиво'=>[0,'Участник'],
 'сник'=>[20,'Помощник'],'ник'=>[20,'Помощник'],'рник'=>[20,'Помощник'],'нлист'=>[20,'Помощник'],'безников'=>[20,'Помощник'],'мут'=>[20,'Помощник'],'унмут'=>[20,'Помощник'],'кик'=>[20,'Помощник'],'пред'=>[20,'Помощник'],'варн'=>[20,'Помощник'],'унварн'=>[20,'Помощник'],'снятьпред'=>[20,'Помощник'],'предупреждения'=>[20,'Помощник'],'getwarns'=>[20,'Помощник'],'getwarn'=>[20,'Помощник'],'getban'=>[20,'Помощник'],'getmute'=>[20,'Помощник'],'warnlist'=>[20,'Помощник'],'преды'=>[20,'Помощник'],'бан'=>[20,'Помощник'],'унбан'=>[20,'Помощник'],'вызов'=>[20,'Помощник'],'чатинфо'=>[20,'Помощник'],'reg'=>[20,'Помощник'],'упоминать'=>[20,'Помощник'],'неупоминать'=>[20,'Помощник'],
 'role'=>[40,'Модератор'],'removerole'=>[40,'Модератор'],'помощник'=>[40,'Модератор'],'модер'=>[40,'Модератор'],'тишина'=>[40,'Модератор'],'понику'=>[40,'Модератор'],'gzov'=>[40,'Модератор'],'gkick'=>[40,'Модератор'],'gsnick'=>[40,'Модератор'],
 'gban'=>[60,'Администратор'],'gunban'=>[60,'Администратор'],'grole'=>[60,'Администратор'],'гмодер'=>[60,'Администратор'],'гпомощник'=>[60,'Администратор'],'удалить'=>[60,'Администратор'],'gm'=>[60,'Администратор'],'removegm'=>[60,'Администратор'],'gms'=>[60,'Администратор'],
 'pin'=>[80,'Ст. администратор'],'unpin'=>[80,'Ст. администратор'],'admin'=>[80,'Ст. администратор'],'gadmin'=>[80,'Ст. администратор'],'newrole'=>[80,'Ст. администратор'],'gnewrole'=>[80,'Ст. администратор'],'delrole'=>[80,'Ст. администратор'],'welcome'=>[80,'Ст. администратор'],'setrules'=>[80,'Ст. администратор'],'delrules'=>[80,'Ст. администратор'],'неактив'=>[80,'Ст. администратор'],'givemoney'=>[80,'Ст. администратор'],'timeuved'=>[80,'Ст. администратор'],
 'settings'=>[100,'Владелец'],'setup'=>[100,'Владелец'],'unity'=>[100,'Владелец'],'addunity'=>[100,'Владелец'],'createunity'=>[100,'Владелец'],'editunity'=>[100,'Владелец'],'removeunity'=>[100,'Владелец'],'sync'=>[100,'Владелец'],'spec'=>[100,'Владелец'],'gspec'=>[100,'Владелец'],'wipe'=>[100,'Владелец'],'games'=>[100,'Владелец'],'editcmd'=>[100,'Владелец'],'geditcmd'=>[100,'Владелец'],'gedit'=>[100,'Владелец'],'gsettings'=>[100,'Владелец'],'owner'=>[100,'Владелец'],'automod'=>[100,'Владелец'],
 'setlog'=>[100,'Владелец'],'zovvv'=>[100,'Владелец'],'addws'=>[100,'Владелец'],'gtimeuvedg'=>[100,'Владелец'],'gzovg'=>[100,'Владелец'],'reportedit'=>[100,'Владелец'],'getdialog'=>[100,'Владелец'],'getreport'=>[100,'Владелец'],'reports'=>[100,'Владелец'],'listunities'=>[100,'Владелец'],'listen'=>[100,'Владелец'],'chatlist'=>[100,'Владелец'],'userchats'=>[100,'Владелец'],'ahistory'=>[100,'Владелец'],'checkban'=>[100,'Владелец']];
 if(!isset($req[$cmd]))return;[$need,$role]=$req[$cmd];if($L<$need){sendMessage($peer,requireLevel($L,$need,$role)??'❌ Недостаточно прав.');return;}
 $argText=trim(implode(' ',$a));
 switch($cmd){
 case 'пинг':case'ping':case'статус':sendMessage($peer,'🏓 RAZE RUSSIA BOT: онлайн');break;
 case 'help':case'помощь':case'команды':case'start':sendHelp($peer);break;
 case 'правила':sendMessage($peer,rulesText($p,$peer));break;
 case 'роли':$rows=$p->query('SELECT name,priority FROM roles ORDER BY priority DESC')->fetchAll();$s="👑 Роли:\n";foreach($rows as $r)$s.="• {$r['name']} ({$r['priority']})\n";sendMessage($peer,$s);break;
 case 'админы':$q=$p->prepare('SELECT u.user_id,r.name,r.priority FROM chat_users u JOIN roles r ON r.id=u.role_id WHERE u.peer_id=? AND r.priority>0 ORDER BY r.priority DESC');$q->execute([$peer]);$s="👮 Администрация:\n";foreach($q as $r)$s.="• ".nameOf((int)$r['user_id'])." — {$r['name']} ({$r['priority']})\n";sendMessage($peer,$s);break;
 case 'онлайн':$m=chatMembers($peer);$online=array_filter($m,fn($x)=>!empty($x['is_admin'])||!empty($x['online']));sendMessage($peer,'🟢 Онлайн участников: '.count($online).' из '.count($m));break;
 case 'myid':sendMessage($peer,"🆔 Ваш VK ID: {$from}");break;case'thereid':case'id':sendMessage($peer,"🆔 ID этой беседы: {$peer}");break;
 case 'report':case'/report':$t=$argText;if($t===''){sendMessage($peer,'Использование: /report [текст]');break;}$p->prepare('INSERT INTO reports(peer_id,user_id,text) VALUES(?,?,?)')->execute([$peer,$from,$t]);$rid=(int)$p->lastInsertId();$s=$p->prepare('SELECT report_notify_peer FROM chat_settings WHERE peer_id=?');$s->execute([$peer]);$np=(int)($s->fetchColumn()?:0);if($np)sendMessage($np,"🆕 Новый репорт #{$rid}\nОт: ".nameOf($from)." ({$from})\n{$t}");sendMessage($peer,"✅ Ваш репорт #{$rid} отправлен администрации. Ожидайте ответа.");break;
 case 'упоминать':$p->prepare('INSERT INTO chat_settings(peer_id,mentions_enabled) VALUES(?,1) ON CONFLICT(peer_id) DO UPDATE SET mentions_enabled=1')->execute([$peer]);sendMessage($peer,'✅ Вы включили упоминание себя в вызовах.');break;case'неупоминать':$p->prepare('INSERT INTO chat_settings(peer_id,mentions_enabled) VALUES(?,0) ON CONFLICT(peer_id) DO UPDATE SET mentions_enabled=0')->execute([$peer]);sendMessage($peer,'✅ Вы отключили упоминание себя в вызовах.');break;
 case 'profile':case'профиль':case'проф':ensureEconomy($p,$peer,$target??$from);$q=$p->prepare('SELECT * FROM economy WHERE peer_id=? AND user_id=?');$q->execute([$peer,$target??$from]);$e=$q->fetch();sendMessage($peer,"👤 Профиль: ".nameOf($target??$from)."\n💰 Баланс: ".number_format((int)$e['balance'],0,'.',' ')." ₽\n🌍 Страна: ".($e['country']?:'не указана')."\n💍 Партнёр: ".($e['partner_id'] ? nameOf((int)$e['partner_id']) : 'нет'));break;
 case 'bonus':case'бонус':ensureEconomy($p,$peer,$from);$q=$p->prepare('SELECT balance,last_bonus FROM economy WHERE peer_id=? AND user_id=?');$q->execute([$peer,$from]);$e=$q->fetch();if($e['last_bonus']&&strtotime($e['last_bonus'])>time()-86400){sendMessage($peer,'⏳ Бонус уже получен. Возвращайтесь через 24 часа.');break;}$p->prepare("UPDATE economy SET balance=balance+1000,last_bonus=datetime('now') WHERE peer_id=? AND user_id=?")->execute([$peer,$from]);sendMessage($peer,'🎁 Вы получили ежедневный бонус: 1 000 ₽!');break;
 case 'казино':$bet=amount($a[0]??'0');ensureEconomy($p,$peer,$from);$q=$p->prepare('SELECT balance FROM economy WHERE peer_id=? AND user_id=?');$q->execute([$peer,$from]);$bal=(int)$q->fetchColumn();if($bet<=0||$bet>$bal){sendMessage($peer,"🎰 Недостаточно средств. Ваш баланс: ".number_format($bal,0,'.',' '));break;}$roll=random_int(1,100);$mult = $roll <= 10 ? 0 : ($roll <= 55 ? 1 : ($roll <= 85 ? 1.5 : 2.5));$delta=(int)round($bet*$mult)-$bet;$p->prepare('UPDATE economy SET balance=balance+?,last_casino=datetime(\'now\') WHERE peer_id=? AND user_id=?')->execute([$delta,$peer,$from]);sendMessage($peer,"🎰 Результат: {$mult}×\n".($delta>=0?'Вы выиграли ':'Вы проиграли ').number_format(abs($delta),0,'.',' ')." ₽");break;
 case 'перевод':$t = $target ?? (isset($a[0]) ? (int)$a[0] : 0);$sum=amount($a[$target?0:1]??'0');if(!$t||$sum<=0){sendMessage($peer,'Использование: !перевод [ID] [сумма]');break;}ensureEconomy($p,$peer,$from);ensureEconomy($p,$peer,$t);$p->beginTransaction();$q=$p->prepare('SELECT balance FROM economy WHERE peer_id=? AND user_id=?');$q->execute([$peer,$from]);$bal=(int)$q->fetchColumn();if($bal<$sum){$p->rollBack();sendMessage($peer,'❌ Недостаточно средств.');break;}$p->prepare('UPDATE economy SET balance=balance-? WHERE peer_id=? AND user_id=?')->execute([$sum,$peer,$from]);$p->prepare('UPDATE economy SET balance=balance+? WHERE peer_id=? AND user_id=?')->execute([$sum,$peer,$t]);$p->commit();sendMessage($peer,"💸 Перевод выполнен: ".number_format($sum,0,'.',' ')." ₽ отправлено пользователю ".nameOf($t).'.');break;
 case 'топ':case'top':$q=$p->prepare('SELECT user_id,balance FROM economy WHERE peer_id=? ORDER BY balance DESC LIMIT 10');$q->execute([$peer]);$s="👑 Топ игроков по балансу:\n";$i=1;foreach($q as $r)$s.=$i++.'. '.nameOf((int)$r['user_id']).' — '.number_format((int)$r['balance'],0,'.',' ')." ₽\n";sendMessage($peer,$s);break;
 case 'atop':$q=$p->query('SELECT user_id,SUM(balance) balance FROM economy GROUP BY user_id ORDER BY balance DESC LIMIT 10');$s="👑 Общий топ:\n";$i=1;foreach($q as $r)$s.=$i++.'. '.nameOf((int)$r['user_id']).' — '.number_format((int)$r['balance'],0,'.',' ')." ₽\n";sendMessage($peer,$s);break;
 case 'гражданство':$country=trim($argText);if($country===''){sendMessage($peer,'Укажите страну.');break;}$p->prepare('UPDATE economy SET country=? WHERE peer_id=? AND user_id=?')->execute([$country,$peer,$from]);$p->prepare('INSERT OR IGNORE INTO countries(peer_id,name,owner_id) VALUES(?,?,?)')->execute([$peer,$country,$from]);sendMessage($peer,"🌍 Гражданство установлено: {$country}");break;case'страна':$q=$p->prepare('SELECT country FROM economy WHERE peer_id=? AND user_id=?');$q->execute([$peer,$from]);sendMessage($peer,'🌍 Ваша страна: '.($q->fetchColumn()?:'не указана'));break;case'страны':$q=$p->prepare('SELECT name,COUNT(*) citizens FROM countries c LEFT JOIN economy e ON e.peer_id=c.peer_id AND e.country=c.name WHERE c.peer_id=? GROUP BY c.name ORDER BY citizens DESC');$q->execute([$peer]);$s="🌍 Страны:\n";foreach($q as $r)$s.="• {$r['name']} — {$r['citizens']} граждан\n";sendMessage($peer,$s?:'Стран пока нет.');break;
 case 'брак':$t=$target??(int)($a[0]??0);if(!$t||$t===$from){sendMessage($peer,'Укажите ID другого пользователя.');break;}ensureEconomy($p,$peer,$from);ensureEconomy($p,$peer,$t);$p->prepare('UPDATE economy SET partner_id=? WHERE peer_id=? AND user_id=?')->execute([$t,$peer,$from]);$p->prepare('UPDATE economy SET partner_id=? WHERE peer_id=? AND user_id=?')->execute([$from,$peer,$t]);$p->prepare('INSERT OR IGNORE INTO marriages(peer_id,user1,user2) VALUES(?,?,?)')->execute([$peer,min($from,$t),max($from,$t)]);sendMessage($peer,'💍 Предложение/брак оформлен с '.nameOf($t).'.');break;case'развод':$q=$p->prepare('SELECT partner_id FROM economy WHERE peer_id=? AND user_id=?');$q->execute([$peer,$from]);$t=(int)($q->fetchColumn()?:0);if($t){$p->prepare('UPDATE economy SET partner_id=NULL WHERE peer_id=? AND user_id IN (?,?)')->execute([$peer,$from,$t]);$p->prepare('DELETE FROM marriages WHERE peer_id=? AND ((user1=? AND user2=?) OR (user1=? AND user2=?))')->execute([$peer,min($from,$t),max($from,$t),max($from,$t),min($from,$t)]);sendMessage($peer,'💔 Брак расторгнут.');}else sendMessage($peer,'Брака нет.');break;case'браки':$q=$p->prepare('SELECT user1,user2 FROM marriages WHERE peer_id=? LIMIT 20');$q->execute([$peer]);$s="💍 Браки:\n";foreach($q as $r)$s.='• '.nameOf((int)$r['user1']).' + '.nameOf((int)$r['user2'])."\n";sendMessage($peer,$s?:'Браков пока нет.');break;
 case 'поцелуй':case'kiss':$t=$target??(int)($a[0]??0);sendMessage($peer,$t?'💋 '.nameOf($from).' поцеловал(а) '.nameOf($t).'.':'Укажите ID.');break;case'обнять':$t=$target??(int)($a[0]??0);sendMessage($peer,$t?'🤗 '.nameOf($from).' обнял(а) '.nameOf($t).'.':'Укажите ID.');break;case'попытка':sendMessage($peer,'🎲 '.nameOf($from).' — '.(random_int(0,1)?'успех!':'неудача!').' Действие: '.$argText);break;case'пиво':sendMessage($peer,'🍺 '.nameOf($from).' выпил(а) виртуальное пиво.');break;
 case 'history':$t=$target??$from;$q=$p->prepare('SELECT action,details,created_at FROM logs WHERE peer_id=? AND target_id=? AND action IN (\'warn\',\'ban\',\'mute\',\'unwarn\',\'unban\',\'unmute\') ORDER BY id DESC LIMIT 20');$q->execute([$peer,$t]);$s="📜 История наказаний: ".nameOf($t)."\n";foreach($q as $r)$s.="• {$r['created_at']} — {$r['action']} — {$r['details']}\n";sendMessage($peer,$s);break;
 case 'сник':case'ник':$t=$target??$from;if($cmd==='ник'&&!$argText){$q=$p->prepare('SELECT nickname FROM nicknames WHERE peer_id=? AND user_id=?');$q->execute([$peer,$t]);sendMessage($peer,'🏷 Ник: '.($q->fetchColumn()?:'не установлен'));break;}$nick=$target ? trim(implode(' ',array_slice($a,1))) : trim($argText);if($nick===''){sendMessage($peer,'Использование: !сник [ID] [ник]');break;}$p->prepare('INSERT INTO nicknames(peer_id,user_id,nickname) VALUES(?,?,?) ON CONFLICT(peer_id,user_id) DO UPDATE SET nickname=excluded.nickname')->execute([$peer,$t,$nick]);sendMessage($peer,'✅ Ник установлен: '.$nick);break;
 case 'рник':$t=$target??$from;$p->prepare('DELETE FROM nicknames WHERE peer_id=? AND user_id=?')->execute([$peer,$t]);sendMessage($peer,'✅ Ник удалён.');break;case'нлист':$q=$p->prepare('SELECT user_id,nickname FROM nicknames WHERE peer_id=? ORDER BY nickname LIMIT 50');$q->execute([$peer]);$s="🏷 Ники:\n";foreach($q as $r)$s.='• '.nameOf((int)$r['user_id']).' — '.$r['nickname']."\n";sendMessage($peer,$s);break;case'безников':$q=$p->prepare('SELECT user_id FROM chat_users WHERE peer_id=? AND user_id NOT IN(SELECT user_id FROM nicknames WHERE peer_id=?) LIMIT 50');$q->execute([$peer,$peer]);$s="👤 Без никнейма:\n";foreach($q as $r)$s.='• '.nameOf((int)$r['user_id'])."\n";sendMessage($peer,$s);break;
 case 'пред':case'варн':$t=$target??(int)($a[0]??0);$reason=trim(implode(' ',array_slice($a,$target?1:1)));if(!$t){sendMessage($peer,'Укажите ID/ответ.');break;}$bad=punishAllowed($p,$peer,$from,$t,20);if($bad){sendMessage($peer,$bad);break;}$q=$p->prepare('SELECT COUNT(*) FROM warnings WHERE peer_id=? AND user_id=? AND active=1');$q->execute([$peer,$t]);$cnt=(int)$q->fetchColumn();if($cnt>=3){sendMessage($peer,'❌ У пользователя уже 3 активных предупреждения.');break;}$p->prepare('INSERT INTO warnings(peer_id,user_id,moderator_id,reason) VALUES(?,?,?,?)')->execute([$peer,$t,$from,$reason?:'Без причины']);sendMessage($peer,nameOf($t)." получил предупреждение (".($cnt+1).'/3). Причина: '.($reason?:'не указана'));break;
 case 'унварн':case'снятьпред':$t=$target??(int)($a[0]??0);if(!$t){sendMessage($peer,'Укажите ID/ответ.');break;}$q=$p->prepare('SELECT id FROM warnings WHERE peer_id=? AND user_id=? AND active=1 ORDER BY id DESC LIMIT 1');$q->execute([$peer,$t]);$id=$q->fetchColumn();if($id){$p->prepare('UPDATE warnings SET active=0 WHERE id=?')->execute([$id]);sendMessage($peer,'✅ Последнее предупреждение снято.');}else sendMessage($peer,'Активных предупреждений нет.');break;
 case 'предупреждения':case'getwarns':$t=$target??(int)($a[0]??0);$q=$p->prepare('SELECT COUNT(*) FROM warnings WHERE peer_id=? AND user_id=? AND active=1');$q->execute([$peer,$t]);sendMessage($peer,'⚠️ Активных предупреждений: '.$q->fetchColumn());break;case'getwarn':$t=$target??(int)($a[0]??0);$q=$p->prepare('SELECT moderator_id,reason,created_at FROM warnings WHERE peer_id=? AND user_id=? ORDER BY id DESC');$q->execute([$peer,$t]);$s='⚠️ Предупреждения '.nameOf($t).":\n";$i=1;foreach($q as $r)$s.=$i++.'. Выдал: '.nameOf((int)$r['moderator_id']).' | '.$r['reason'].' | '.$r['created_at']."\n";sendMessage($peer,$s);break;case'getban':$t=$target??(int)($a[0]??0);$q=$p->prepare('SELECT moderator_id,days,reason,created_at,expires_at,active FROM bans WHERE peer_id=? AND user_id=? ORDER BY id DESC');$q->execute([$peer,$t]);$s='🔨 Баны '.nameOf($t).":\n";foreach($q as $r)$s.='• '.($r['active']?'активен':'снят').' | выдал '.nameOf((int)$r['moderator_id']).' | '.$r['days'].' дн. | до '.$r['expires_at'].' | '.$r['reason']."\n";sendMessage($peer,$s);break;case'getmute':$t=$target??(int)($a[0]??0);$q=$p->prepare('SELECT moderator_id,minutes,reason,created_at,expires_at,active FROM mutes WHERE peer_id=? AND user_id=? ORDER BY id DESC');$q->execute([$peer,$t]);$s='🔇 Муты '.nameOf($t).":\n";foreach($q as $r)$s.='• '.($r['active']?'активен':'снят').' | выдал '.nameOf((int)$r['moderator_id']).' | '.$r['minutes'].' мин. | до '.$r['expires_at'].' | '.$r['reason']."\n";sendMessage($peer,$s);break;
 case 'warnlist':case'преды':$q=$p->prepare('SELECT user_id,COUNT(*) c FROM warnings WHERE peer_id=? AND active=1 GROUP BY user_id ORDER BY c DESC');$q->execute([$peer]);$s="⚠️ Список варнов:\n";foreach($q as $r)$s.='• '.nameOf((int)$r['user_id']).' — '.$r['c']."\n";sendMessage($peer,$s);break;
 case 'мут':$t=$target??(int)($a[0]??0);$idx=$target?0:1;$mins=(int)($a[$idx]??0);if(!$t||$mins<=0){sendMessage($peer,'Использование: !мут [ID] [минуты] [причина]');break;}$bad=punishAllowed($p,$peer,$from,$t,20);if($bad){sendMessage($peer,$bad);break;}$reason=trim(implode(' ',array_slice($a,$idx+1)))?:'Без причины';$exp=date('Y-m-d H:i:s',time()+$mins*60);$p->prepare('INSERT INTO mutes(peer_id,user_id,moderator_id,minutes,reason,expires_at) VALUES(?,?,?,?,?,?)')->execute([$peer,$t,$from,$mins,$reason,$exp]);sendMessage($peer,"🔇 ".nameOf($t)." получил мут на {$mins} мин. Причина: {$reason}");break;case'унмут':$t=$target??(int)($a[0]??0);$p->prepare('UPDATE mutes SET active=0 WHERE peer_id=? AND user_id=? AND active=1')->execute([$peer,$t]);sendMessage($peer,'🔊 Мут снят.');break;
 case 'кик':$t=$target??(int)($a[0]??0);$bad=punishAllowed($p,$peer,$from,$t,20);if($bad){sendMessage($peer,$bad);break;}$r=vk('messages.removeChatUser',['chat_id'=>$peer-2000000000,'member_id'=>$t]);sendMessage($peer,isset($r['response'])?'👢 Пользователь исключён.':'❌ VK: '.($r['error']['error_msg']??'ошибка'));break;
 case 'бан':$t=$target??(int)($a[0]??0);$idx=$target?0:1;$days=(int)($a[$idx]??0);if(!$t||$days<=0){sendMessage($peer,'Использование: !бан [ID] [дни] [причина]');break;}$bad=punishAllowed($p,$peer,$from,$t,40);if($bad){sendMessage($peer,$bad);break;}$reason=trim(implode(' ',array_slice($a,$idx+1)))?:'не указана';$exp=date('Y-m-d H:i:s',time()+$days*86400);$p->prepare('INSERT INTO bans(peer_id,user_id,moderator_id,days,reason,expires_at) VALUES(?,?,?,?,?,?)')->execute([$peer,$t,$from,$days,$reason,$exp]);sendMessage($peer,"🔨 ".nameOf($t)." заблокирован на {$days} дн.\nПричина: {$reason}");break;case'унбан':$t=$target??(int)($a[0]??0);$p->prepare('UPDATE bans SET active=0 WHERE peer_id=? AND user_id=? AND active=1')->execute([$peer,$t]);sendMessage($peer,'✅ Бан снят.');break;
 case 'вызов':mentionAll($p,$peer,$argText?:'📢 Вызов участников!');break;case'чатинфо':$m=chatMembers($peer);$q=$p->prepare('SELECT COUNT(*) FROM chat_users WHERE peer_id=?');$q->execute([$peer]);sendMessage($peer,'ℹ️ ID: '.$peer."\nУчастников VK: ".count($m)."\nПользователей в базе: ".$q->fetchColumn());break;case'reg':$t=$target??(int)($a[0]??$from);$q=$p->prepare('SELECT registered_at FROM economy WHERE peer_id=? AND user_id=?');$q->execute([$peer,$t]);sendMessage($peer,'📅 Регистрация: '.($q->fetchColumn()?:'нет данных'));break;
 case 'role':$t=$target??(int)($a[0]??0);$rn=trim(implode(' ',array_slice($a,$target?1:1)));$rid=null;if(is_numeric($rn)){$q=$p->prepare('SELECT id FROM roles WHERE priority=?');$q->execute([(int)$rn]);$rid=$q->fetchColumn();}else{$q=$p->prepare('SELECT id FROM roles WHERE name=?');$q->execute([$rn]);$rid=$q->fetchColumn();}if(!$t||!$rid){sendMessage($peer,'Использование: !role [ID] [роль/приоритет]');break;}$p->prepare('INSERT INTO chat_users(peer_id,user_id,role_id) VALUES(?,?,?) ON CONFLICT(peer_id,user_id) DO UPDATE SET role_id=excluded.role_id')->execute([$peer,$t,$rid]);sendMessage($peer,'👑 Роль выдана.');break;case'removerole':$t=$target??(int)($a[0]??0);$p->prepare('UPDATE chat_users SET role_id=1 WHERE peer_id=? AND user_id=?')->execute([$peer,$t]);sendMessage($peer,'✅ Все роли сняты.');break;case'помощник':case'модер':$t=$target??(int)($a[0]??0);$r=$cmd==='помощник'?2:3;$p->prepare('UPDATE chat_users SET role_id=? WHERE peer_id=? AND user_id=?')->execute([$r,$peer,$t]);sendMessage($peer,'👑 Роль назначена.');break;
 case 'тишина':$mins=(int)($a[0]??0);if(!$mins){$mins=30;}if(str_contains(mb_strtolower($argText),'час'))$mins=(int)preg_replace('/\D/','',$argText)*60;if(str_contains(mb_strtolower($argText),'дн'))$mins=(int)preg_replace('/\D/','',$argText)*1440;$until=date('Y-m-d H:i:s',time()+$mins*60);$p->prepare('INSERT INTO chat_settings(peer_id,silence_until) VALUES(?,?) ON CONFLICT(peer_id) DO UPDATE SET silence_until=excluded.silence_until')->execute([$peer,$until]);sendMessage($peer,"🔇 Режим тишины включён до {$until}.");break;
 case 'понику':$part=mb_strtolower($argText);$q=$p->prepare('SELECT user_id,nickname FROM nicknames WHERE peer_id=? AND lower(nickname) LIKE ? LIMIT 20');$q->execute([$peer,'%'.$part.'%']);$s='🔎 Поиск:\n';foreach($q as $r)$s.='• '.nameOf((int)$r['user_id']).' — '.$r['nickname']."\n";sendMessage($peer,$s);break;
 case 'gsnick':$t=(int)($a[0]??0);$nick=trim(implode(' ',array_slice($a,1)));if(!$t||$nick===''){sendMessage($peer,'Использование: !gsnick [ID] [ник]');break;}doGlobal($p,$peer,$from,'gsnick',function(int $c)use($p,$t,$nick){$p->prepare('INSERT INTO nicknames(peer_id,user_id,nickname) VALUES(?,?,?) ON CONFLICT(peer_id,user_id) DO UPDATE SET nickname=excluded.nickname')->execute([$c,$t,$nick]);});sendMessage($peer,'✅ Ник установлен во всех известных беседах.');break;case'gzov':case'zovvv':case'gzovg':mentionAll($p,$peer,$argText?:'📢 Общий вызов!');break;case'gkick':$t=(int)($a[0]??0);doGlobal($p,$peer,$from,'gkick',function(int $c)use($t){vk('messages.removeChatUser',['chat_id'=>$c-2000000000,'member_id'=>$t]);});sendMessage($peer,'👢 Выполнено во всех известных беседах.');break;
 case 'gban':case'gunban':$t=(int)($a[0]??0);$days=(int)($a[1]??0);doGlobal($p,$peer,$from,$cmd,function(int $c)use($p,$from,$t,$days,$cmd,$argText){if($cmd==='gban'){$exp=date('Y-m-d H:i:s',time()+max(1,$days)*86400);$p->prepare('INSERT INTO bans(peer_id,user_id,moderator_id,days,reason,expires_at) VALUES(?,?,?,?,?,?)')->execute([$c,$t,$from,max(1,$days),$argText,$exp]);}else{$p->prepare('UPDATE bans SET active=0 WHERE peer_id=? AND user_id=?')->execute([$c,$t]);}});sendMessage($peer,'🌐 Глобальная блокировка обработана.');break;
 case 'grole':case'гмодер':case'гпомощник':$t=(int)($a[0]??0);$rn=$cmd==='гмодер'?3:2;if($cmd==='grole'){$rn=(int)($a[1]??3);}doGlobal($p,$peer,$from,$cmd,function(int $c)use($p,$t,$rn){$p->prepare('UPDATE chat_users SET role_id=? WHERE peer_id=? AND user_id=?')->execute([$rn,$c,$t]);});sendMessage($peer,'🌐 Глобальная роль обработана.');break;
 case 'удалить':$cm=$peer-2000000000;$mid=(int)($o['conversation_message_id']??0);if(!$mid&&isset($o['reply_message']['conversation_message_id']))$mid=(int)$o['reply_message']['conversation_message_id'];if(!$mid){sendMessage($peer,'Ответьте на сообщение, которое нужно удалить.');break;} $r=vk('messages.delete',['cmids'=>$mid,'delete_for_all'=>1,'peer_id'=>$peer]);sendMessage($peer,isset($r['response'])?'🗑 Сообщение удалено.':'❌ VK: '.($r['error']['error_msg']??'ошибка'));break;
 case 'gm':$t=$target??(int)($a[0]??0);$p->prepare('UPDATE chat_users SET immunity=CASE WHEN immunity=1 THEN 0 ELSE 1 END WHERE peer_id=? AND user_id=?')->execute([$peer,$t]);$q=$p->prepare('SELECT immunity FROM chat_users WHERE peer_id=? AND user_id=?');$q->execute([$peer,$t]);sendMessage($peer,((int)$q->fetchColumn()===1?'🛡 Иммунитет включён.':'🛡 Иммунитет снят.'));break;case'removegm':$t=$target??(int)($a[0]??0);$p->prepare('UPDATE chat_users SET immunity=0 WHERE peer_id=? AND user_id=?')->execute([$peer,$t]);sendMessage($peer,'🛡 Иммунитет снят.');break;case'gms':$q=$p->prepare('SELECT user_id FROM chat_users WHERE peer_id=? AND immunity=1');$q->execute([$peer]);$s='🛡 Иммунитет:\n';foreach($q as $r)$s.='• '.nameOf((int)$r['user_id'])."\n";sendMessage($peer,$s);break;
 case 'pin':$mid=(int)($o['reply_message']['conversation_message_id']??0);if(!$mid){sendMessage($peer,'📌 Ответьте на сообщение, которое нужно закрепить.');break;}$r=vk('messages.pin',['peer_id'=>$peer,'conversation_message_id'=>$mid]);sendMessage($peer,isset($r['response'])?'📌 Сообщение закреплено.':'❌ Не удалось закрепить: '.($r['error']['error_msg']??'ошибка VK'));break;case'unpin':$r=vk('messages.unpin',['peer_id'=>$peer]);sendMessage($peer,isset($r['response'])?'📌 Сообщение откреплено.':'❌ Не удалось открепить: '.($r['error']['error_msg']??'ошибка VK'));break;
 case 'admin':case'gadmin':$t=(int)($a[0]??0);$r=5;doGlobal($p,$peer,$from,$cmd,function(int $c)use($p,$t,$r){$p->prepare('UPDATE chat_users SET role_id=? WHERE peer_id=? AND user_id=?')->execute([$r,$c,$t]);});sendMessage($peer,'👑 Администратор назначен.');break;
 case 'newrole':case'gnewrole':$pr=(int)($a[0]??0);$rn=trim(implode(' ',array_slice($a,1)));if($rn===''||$pr<0){sendMessage($peer,'Использование: !newrole [приоритет] [название]');break;}$p->prepare('INSERT INTO roles(name,priority) VALUES(?,?) ON CONFLICT(name) DO UPDATE SET priority=excluded.priority')->execute([$rn,$pr]);sendMessage($peer,'✅ Роль создана/обновлена.');break;case'delrole':$pr=(int)($a[0]??-1);$p->prepare('DELETE FROM roles WHERE priority=? AND id>6')->execute([$pr]);sendMessage($peer,'✅ Роль удалена.');break;
 case 'welcome':$p->prepare('INSERT INTO chat_settings(peer_id,welcome) VALUES(?,?) ON CONFLICT(peer_id) DO UPDATE SET welcome=excluded.welcome')->execute([$peer,$argText]);sendMessage($peer,'✅ Приветствие сохранено.');break;case'setrules':$p->prepare('INSERT INTO chat_settings(peer_id,rules) VALUES(?,?) ON CONFLICT(peer_id) DO UPDATE SET rules=excluded.rules')->execute([$peer,$argText]);sendMessage($peer,'✅ Правила сохранены.');break;case'delrules':$p->prepare('UPDATE chat_settings SET rules=NULL WHERE peer_id=?')->execute([$peer]);sendMessage($peer,'✅ Правила удалены.');break;case'неактив':$days=(int)($a[0]??3);$q=$p->prepare("SELECT user_id,last_seen FROM chat_users WHERE peer_id=? AND last_seen<=datetime('now',?) LIMIT 50");$q->execute([$peer,'-'.$days.' days']);$s="💤 Неактивные за {$days} дн.:\n";foreach($q as $r)$s.='• '.nameOf((int)$r['user_id']).' — '.$r['last_seen']."\n";sendMessage($peer,$s);break;
 case 'givemoney':$t=(int)($a[0]??0);$sum=amount($a[1]??'0');ensureEconomy($p,$peer,$t);$p->prepare('UPDATE economy SET balance=balance+? WHERE peer_id=? AND user_id=?')->execute([$sum,$peer,$t]);sendMessage($peer,'💰 Выдано '.number_format($sum,0,'.',' ').' ₽.');break;case'timeuved':$v=$a[0]??'0';$mins=(int)$v;if(str_contains(mb_strtolower($v),'ч'))$mins=(int)$v*60;$msg=trim(implode(' ',array_slice($a,1)));if($mins<=0||$msg===''){sendMessage($peer,'Использование: !timeuved 2 текст');break;}$next=date('Y-m-d H:i:s',time()+$mins*60);$p->prepare('INSERT INTO schedules(peer_id,owner_id,every_minutes,text,next_at) VALUES(?,?,?,?,?)')->execute([$peer,$from,$mins,$msg,$next]);sendMessage($peer,'⏰ Автоуведомление создано.');break;
 case 'settings':$q=$p->prepare('SELECT * FROM chat_settings WHERE peer_id=?');$q->execute([$peer]);$r=$q->fetch()?:[];sendMessage($peer,'⚙️ Настройки:\nGames: '.(!empty($r['games_enabled'])?'ON':'OFF')."\nAutoMod: ".(!empty($r['automod_enabled'])?'ON':'OFF')."\nMentions: ".(!empty($r['mentions_enabled'])?'ON':'OFF'));break;case'setup':$p->prepare('INSERT OR IGNORE INTO chat_settings(peer_id,rules,welcome,games_enabled,mentions_enabled) VALUES(?,\'Правила беседы ещё не настроены.\',\'Добро пожаловать в RAZE RUSSIA!\',0,1)')->execute([$peer]);sendMessage($peer,'✅ Первичная настройка выполнена.');break;case'games':$p->prepare('INSERT INTO chat_settings(peer_id,games_enabled) VALUES(?,1) ON CONFLICT(peer_id) DO UPDATE SET games_enabled=CASE WHEN games_enabled=1 THEN 0 ELSE 1 END')->execute([$peer]);$q=$p->prepare('SELECT games_enabled FROM chat_settings WHERE peer_id=?');$q->execute([$peer]);sendMessage($peer,'🎮 Игры: '.((int)$q->fetchColumn()?'включены':'выключены'));break;case'automod':$p->prepare('INSERT INTO chat_settings(peer_id,automod_enabled) VALUES(?,1) ON CONFLICT(peer_id) DO UPDATE SET automod_enabled=CASE WHEN automod_enabled=1 THEN 0 ELSE 1 END')->execute([$peer]);sendMessage($peer,'🛡 Автомод переключён.');break;
 case 'wipe':$p->prepare('DELETE FROM nicknames WHERE peer_id=?')->execute([$peer]);$p->prepare('UPDATE bans SET active=0 WHERE peer_id=?')->execute([$peer]);$p->prepare('UPDATE warnings SET active=0 WHERE peer_id=?')->execute([$peer]);sendMessage($peer,'🧹 Ники, баны и предупреждения сброшены.');break;case'sync':foreach(chatMembers($peer) as $m)if(isset($m['member_id']))ensureUser($p,$peer,(int)$m['member_id']);sendMessage($peer,'🔄 Участники синхронизированы.');break;case'owner':$t=(int)($a[0]??0);$p->prepare('UPDATE chat_users SET role_id=1 WHERE peer_id=? AND user_id!=? AND role_id=6')->execute([$peer,$t]);$p->prepare('UPDATE chat_users SET role_id=6 WHERE peer_id=? AND user_id=?')->execute([$peer,$t]);sendMessage($peer,'👑 Владелец назначен.');break;case'spec':case'gspec':$t=(int)($a[0]??0);$p->prepare('UPDATE chat_users SET role_id=6 WHERE peer_id=? AND user_id=?')->execute([$peer,$t]);sendMessage($peer,'⭐ Главный администратор назначен.');break;case'addws':$t=(int)($a[0]??0);$p->prepare('INSERT OR IGNORE INTO superusers(user_id) VALUES(?)')->execute([$t]);sendMessage($peer,'🛡 Супер-доступ выдан.');break;
 case 'unity':case'createunity':$name=$argText?:'RAZE Unity';$p->prepare('INSERT OR IGNORE INTO unities(name,owner_id) VALUES(?,?)')->execute([$name,$from]);$q=$p->prepare('SELECT id FROM unities WHERE name=?');$q->execute([$name]);$u=(int)$q->fetchColumn();$p->prepare('INSERT OR IGNORE INTO unity_chats(unity_id,peer_id) VALUES(?,?)')->execute([$u,$peer]);sendMessage($peer,"🌐 Объединение '{$name}' готово.");break;case'addunity':$q=$p->query('SELECT id FROM unities ORDER BY id DESC LIMIT 1');$u=(int)$q->fetchColumn();if($u){$p->prepare('INSERT OR IGNORE INTO unity_chats(unity_id,peer_id) VALUES(?,?)')->execute([$u,$peer]);sendMessage($peer,'🌐 Беседа добавлена в объединение.');}else sendMessage($peer,'Сначала создайте объединение.');break;case'removeunity':$p->prepare('DELETE FROM unity_chats WHERE peer_id=?')->execute([$peer]);sendMessage($peer,'🌐 Беседа удалена из объединения.');break;case'editunity':sendMessage($peer,'🌐 Для переименования: !editunity новое название.');break;case'listunities':$q=$p->query('SELECT id,name,owner_id FROM unities ORDER BY id');$s='🌐 Объединения:\n';foreach($q as $r)$s.="• #{$r['id']} {$r['name']} — owner {$r['owner_id']}\n";sendMessage($peer,$s);break;
 case 'setlog':$v=(int)($a[0]??0);$p->prepare('INSERT INTO bot_meta(k,v) VALUES(\'log_peer\',?) ON CONFLICT(k) DO UPDATE SET v=excluded.v')->execute([(string)$v]);sendMessage($peer,$v?'📋 Лог-чат установлен.':'📋 Лог-чат отключён.');break;case'gtimeuvedg':$v=(int)($a[0]??0);$msg=trim(implode(' ',array_slice($a,1)));if($v>0&&$msg!==''){foreach($p->query('SELECT peer_id FROM chat_settings')->fetchAll(PDO::FETCH_COLUMN) as $c)$p->prepare('INSERT INTO schedules(peer_id,owner_id,every_minutes,text,next_at,global_flag) VALUES(?,?,?,?,?,1)')->execute([(int)$c,$from,$v*60,$msg,date('Y-m-d H:i:s',time()+$v*3600)]);sendMessage($peer,'🌐 Глобальное уведомление создано.');}else sendMessage($peer,'Использование: !gtimeuvedg [часы] [текст]');break;
 case 'reportedit':$sub=$a[0]??'';if($sub==='toggle'){$p->prepare('INSERT INTO bot_meta(k,v) VALUES(\'reports_enabled\',\'1\') ON CONFLICT(k) DO UPDATE SET v=CASE WHEN v=\'1\' THEN \'0\' ELSE \'1\' END')->execute([]);sendMessage($peer,'📨 Уведомления репортов переключены.');}elseif($sub==='notify'){$p->prepare('INSERT INTO chat_settings(peer_id,report_notify_peer) VALUES(?,?) ON CONFLICT(peer_id) DO UPDATE SET report_notify_peer=excluded.report_notify_peer')->execute([$peer,(int)($a[1]??0)]);sendMessage($peer,'📨 Чат уведомлений установлен.');}else sendMessage($peer,'Использование: !reportedit toggle / !reportedit notify [peerId]');break;
 case 'reports':$q=$p->query("SELECT id,peer_id,user_id,text,created_at FROM reports WHERE status='open' ORDER BY id DESC LIMIT 20");$s='📨 Открытые тикеты:\n';foreach($q as $r)$s.="#{$r['id']} | peer {$r['peer_id']} | ".nameOf((int)$r['user_id'])." | {$r['text']}\n";sendMessage($peer,$s);break;case'getreport':$id=(int)($a[0]??0);$q=$p->prepare('SELECT * FROM reports WHERE id=?');$q->execute([$id]);$r=$q->fetch();if(!$r){sendMessage($peer,'Тикет не найден.');break;}sendMessage($peer,"📨 Тикет #{$id}\nСтатус: {$r['status']}\nАвтор: ".nameOf((int)$r['user_id'])."\nТекст: {$r['text']}\nКоманды: !getdialog {$id} / !getreport {$id}");break;case'getdialog':$id=(int)($a[0]??0);$q=$p->prepare('SELECT * FROM report_messages WHERE report_id=? ORDER BY id');$q->execute([$id]);$s="💬 Диалог тикета #{$id}:\n";foreach($q as $r)$s.=nameOf((int)$r['user_id']).": {$r['text']}\n";sendMessage($peer,$s);break;
 case 'listen':$v=$a[0]??'';if(strtolower($v)==='stop'){$p->exec('DELETE FROM listenings');sendMessage($peer,'👂 Прослушки остановлены.');break;}$lp=(int)$v;if($lp){$p->prepare('INSERT INTO listenings(peer_id,owner_id,expires_at) VALUES(?,?,?) ON CONFLICT(peer_id) DO UPDATE SET owner_id=excluded.owner_id,expires_at=excluded.expires_at')->execute([$lp,$from,date('Y-m-d H:i:s',time()+86400)]);sendMessage($peer,'👂 Прослушка включена на 24 часа.');}else sendMessage($peer,'Использование: !listen [peerId] или !listen stop');break;case'chatlist':$q=$p->query('SELECT peer_id FROM chat_settings ORDER BY peer_id');$s='💬 Беседы:\n';foreach($q as $r)$s.='• '.$r['peer_id']."\n";sendMessage($peer,$s);break;case'userchats':$t=$target??(int)($a[0]??0);$q=$p->prepare('SELECT DISTINCT peer_id FROM chat_users WHERE user_id=?');$q->execute([$t]);$s='💬 Беседы пользователя:\n';foreach($q as $r)$s.='• '.$r['peer_id']."\n";sendMessage($peer,$s);break;case'ahistory':$t=$target??(int)($a[0]??0);$q=$p->prepare('SELECT peer_id,action,details,created_at FROM logs WHERE target_id=? AND action IN (\'warn\',\'ban\',\'mute\') ORDER BY id DESC LIMIT 30');$q->execute([$t]);$s='📜 Глобальная история:\n';foreach($q as $r)$s.='• '.$r['peer_id'].' '.$r['action'].' '.$r['details'].' '.$r['created_at']."\n";sendMessage($peer,$s);break;case'checkban':$t=$target??(int)($a[0]??0);$q=$p->prepare('SELECT peer_id,days,reason,expires_at FROM bans WHERE user_id=? AND active=1');$q->execute([$t]);$s='🔨 Активные блокировки:\n';foreach($q as $r)$s.='• '.$r['peer_id'].' — '.$r['days'].' дн. до '.$r['expires_at'].' — '.$r['reason']."\n";sendMessage($peer,$s);break;
 case 'editcmd':case'geditcmd':sendMessage($peer,'⚙️ Изменение приоритета команд доступно в полной панели настроек; текущая версия хранит стандартные приоритеты.');break;case'gedit':sendMessage($peer,'⚙️ Используйте !welcome или !setrules для текстовых настроек.');break;case'gsettings':sendMessage($peer,'⚙️ Глобальные настройки: игры/тишина/упоминания/автомод хранятся в базе бесед.');break;
 default:sendMessage($peer,'❓ Команда пока не имеет отдельного обработчика.');
 }
}

function lp():array{global $groupId;for($i=0;$i<5;$i++){$r=vk('groups.getLongPollServer',['group_id'=>$groupId]);if(isset($r['response']))return$r['response'];sleep(2);}throw new RuntimeException('Cannot get VK Long Poll server');}

fwrite(STDOUT,"RAZE RUSSIA VK BOT FULL BUILD started.\n");startupCheck();
while(true){try{$s=lp();$key=$s['key'];$server=$s['server'];$ts=$s['ts'];while(true){sendScheduled($pdo);$u=$server.'?act=a_check&key='.rawurlencode($key).'&wait=25&ts='.rawurlencode($ts);$c=stream_context_create(['http'=>['timeout'=>35,'ignore_errors'=>true]]);$r=@file_get_contents($u,false,$c);if($r===false)throw new RuntimeException('Long Poll connection failed');$d=json_decode($r,true);if(!is_array($d))throw new RuntimeException('Invalid Long Poll response');if(isset($d['ts']))$ts=$d['ts'];if(isset($d['failed']))break;foreach(($d['updates']??[])as$x){if(($x['type']??'')!=='message_new')continue;$o=$x['object']??[];if(isset($o['message'])&&is_array($o['message']))$o=$o['message'];$peer=(int)($o['peer_id']??0);if($peer>=2000000001)handleChatAction($pdo,$peer,$o);handle($pdo,$o);}}}catch(Throwable$e){fwrite(STDERR,'WARN: '.$e->getMessage()."\n");sleep(3);}}